version: '3.8'
services:
  api:
    build:
      context: .      # Path to root
      dockerfile: Dockerfile # Path to Dockerfile relative to context (../Dockerfile means root)
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
  ui:
    build:
      context: ./rpsls.ui
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
    - REACT_APP_API_BASE=http://api:80/api